### ISSUE TITLE
PTDF() uses branch names but bus numbers as lookups

### ISSUE THREAD

**Issue by DillonJ** [NREL-SIIP/PowerSystems.jl#446]
Prior to the move away from Axis arrays, you could index PTDF values using the bus name. From the comment in the code below, it looks like the intention was to also use bus names, but bus numbers are used instead. The lookup for bus numbers is actually bus_number -> bus_number which isn't particularly useful.

https://github.com/NREL/PowerSystems.jl/blob/master/src/utils/network_calculations/ptdf_calculations.jl
```
#Get axis names
    line_ax = [get_name(branch) for branch in branches]
    bus_ax = [get_number(bus) for bus in nodes]
```

I have the feeling it should have been 

```
#Get axis names
    line_ax = [get_name(branch) for branch in branches]
    bus_ax = [get_name(bus) for bus in nodes]
```

**Comment by claytonpbarrows** [comment]
I believe that this was intentional (@daniel-thom or @jd-lara, can you confirm?). The lookup for bus numbers is more accurately described as bus.number -> bus_id, where the bus.number has no requirements on order or contiguity. If this is valuable, we could consider providing an alternative constructor that indexes by bus name rather than number.
In the meantime, there is a suggested workaround in [this example](https://nbviewer.jupyter.org/github/NREL-SIIP/SIIPExamples.jl/blob/master/notebook/PowerSystems_examples/network_matrices.ipynb):

```julia
busname2num = get_components(Bus,sys) |> (c -> Dict(zip(get_name.(c), get_number.(c))))
ptdf["5", busname2num["bus3"]]
```

**Comment by jd-lara** [comment]
@DillonJ you can also access the PTDF values directly using the branch and bus objects no need to use the number or name.

**Comment by claytonpbarrows** [comment]
An example of the suggestion for @jd-lara:
```julia
buses = collect(get_components(Bus,sys))
ptdf["5", buses[3]]
```

**Comment by DillonJ** [comment]
Thanks for the info folks - so I can access the PTDF values fine. The only issue is that my node objects only have a name and not an id - I have to create an arbitrary one for PowerSystems. 

Is there any reason a bus ID has to be a number (except that certain commercial load flow tools expect this?).

Before I was able to access the PTDFs directly using "name". Now I have to create a copy of the PTDFs which are indexed by name, which is a bit of a pity - so it would be nice if either the bus ID could be alpha-numeric or if there was a method to access the values by line and bus names.

Thanks again for the help.

**Comment by claytonpbarrows** [comment]
We require that the bus ID is numeric (::Int) to improve the performance of PowerSystems. We only require this for bus components because buses are the only component that require fast indexing for the vast majority fo power systems modeling. 
Some (all?) of our parsing pathways auto convert/populate bus ID's based on a bus name, or simply the row number in a table. I don't know of many power system data formats that don't include a numeric bus index, but it's pretty trivial to make an index:
```julia
for (id, b) in enumerate(get_components(Bus, sys))
       b.number = id
end
```
Let me know what you think. If this is needed, we can think about solutions.

**Comment by jd-lara** [comment]
@DillonJ we can close this if the reply of @claytonpbarrows is satisfactory, otherwise please reopen the issue.
