### ISSUE TITLE
Excessive printing for arrays of components

### ISSUE THREAD

**Issue by raphaelsaavedra** [NREL-SIIP/PowerSystems.jl#616]
This is more of a nuisance than a bug but it's severe enough to cause terminal crashes more than once.

Suppose I want to get an array with all generators in a system. Doing a simple `gens = get_components(ThermalGen, system)` does the job. The problem is that this prints the full properties of each of the tens of thousands of components, which can cause problems ranging from some minor annoyance to a terminal crash.

Perhaps extending `Base.show` for these arrays (in fact, I think in this case it would be `FlattenIteratorWrapper`) would solve the issue.

**Comment by nickrobinson251** [comment]
> prints the full properties of each of the tens of thousands of components

Do components overload `show`? Perhaps they need to use the `compact` functionality to have a compact representation in Vectors

**Comment by raphaelsaavedra** [comment]
>Do components overload `show`?

Yes, and I think this feature comes from InfrastructureSystems, not PowerSystems, so apologies for the issue in the wrong repo. 

Also, if I understand correctly, there is already some security measures about this in [here](https://github.com/NREL-SIIP/InfrastructureSystems.jl/blob/16ea0803435b2236b5654eead4fa58bca315d7df/src/utils/print.jl) via `MAX_SHOW_COMPONENTS`.

**Comment by raphaelsaavedra** [comment]
This can also be avoided by using `gens = collect(get_components(ThermalGen, system))`, which prints only the name and type of each component, but it's still bad that forgetting to add the `collect` can cause a crash

**Comment by daniel-thom** [comment]
I'm surprised that this causes a crash; it is definitely an annoyance that we've been meaning to fix.  It seems that we need to do something like `show(IOContext(io, :compact => true, :limit=>true), components)`.

I'll implement this in InfrastructureSystems.  As a workaround you can also add `;` after your statement.

**Comment by raphaelsaavedra** [comment]
> I'm surprised that this causes a crash

The crash part might be more on VSCode than on you guys :)

**Comment by daniel-thom** [comment]
I'm sure that we are exceeding what someone thought was a reasonable buffer limit.

**Comment by daniel-thom** [comment]
The changes in the PR above will lessen the output but will probably not fix the crash you saw.  The behavior with the standard library's `Iterators.Flatten` is not great with our components.  We create an iterator out of value iterators of component-concrete-type-dictionaries. `Base.show` will truncate output but only within each sub-container within the iterator - not across sub-containers.  Calling `get_components(Component, sys)` is the worst case.  You'll see some number of component-type1, `...`, more component-type1, then component-type2, `...`, and so on.  Because each component has lots of fields this can be a huge amount of text.  Calling `get_components` on a concrete type won't be as bad.

The same problem could probably happen with lots of Julia containers.  We could workaround this one very common situation by re-implementing `Base.show` for our internal struct that we use to wrap `Iterators.Flatten` and truncate all of the output (as @raphaelsaavedra mentioned).  Perhaps the only text that is valuable for the user is the count of each component type.

**Comment by raphaelsaavedra** [comment]
Thanks for looking into this!

> Perhaps the only text that is valuable for the user is the count of each component type

I agree; the current print is hardly helpful tbh, and if the objective is to look at information in each component, there are better ways of doing this

**Comment by daniel-thom** [comment]
This has been fixed in the PR above.  I'll leave the issue open until a tagged release is available.
