### ISSUE TITLE
Simplify use of Time Series

### ISSUE THREAD

**Issue by andrewrosemberg** [NREL-SIIP/PowerSystems.jl#675]
I'm trying to add a generator in the RTS system with MarketBid forecasts to run a simple simulation of 24h in the day `2020-09-01`, but I'm unable to. I want to avoid having to add a year's worth of meaningless data to be able to run this.

MWE:
```julia
using PowerSystems
const PSY = PowerSystems
using PowerSystems: UtilsData
using Dates
using TimeSeries
using Random
using CSV
using DataFrames
using DataStructures

const initial_time = DateTime("2020-09-01")
const DISPATCH_INCREASE = 2.0
const FIX_DECREASE = 0.3

rts_dir = download("https://github.com/GridMod/RTS-GMLC", "master", pwd())
rts_src_dir = joinpath(rts_dir, "RTS_Data", "SourceData")
rts_siip_dir = joinpath(rts_dir, "RTS_Data", "FormattedData", "SIIP");

rawsys = PSY.PowerSystemTableData(
    rts_src_dir,
    100.0,
    joinpath(rts_siip_dir, "user_descriptors.yaml"),
    timeseries_metadata_file = joinpath(rts_siip_dir, "timeseries_pointers.json"),
    generator_mapping_file = joinpath(rts_siip_dir, "generator_mapping.yaml"),
)

sys_DA = System(rawsys; time_series_resolution = Dates.Hour(1))
transform_single_time_series!(sys_DA, 24, Hour(24))

bus = get_component(Bus, sys_DA, "Abel")
generator = ThermalStandard(
    name = "Invenia",
    available = true,
    status = true,
    bus = bus,
    active_power = 0.0,
    reactive_power = 1.50,
    rating = 0.75,
    prime_mover = PrimeMovers.ST,
    fuel = ThermalFuels.COAL,
    active_power_limits = (min = 0.0, max = 1.0),
    reactive_power_limits = (min = -4.50, max = 4.50),
    time_limits = (up = 0.0, down = 0.0),
    ramp_limits = (up = 9999.0, down = 9999.0),
    operation_cost = MarketBidCost(
        nothing,
        0.0,
        (hot = 0.0, warm = 0.0, cold = 0.0),
        0.0,
        Vector{Service}()
        ),
    base_power = 100.0,
)
add_component!(sys_DA, generator)

bids = 
    [
        [(0.0, 0.0), (0.0, 1.0)],
        fill([(0.0, 0.0), (99999.0, 1.0)], 23)...
]

data = Dict(initial_time => bids)

time_series_data = Deterministic(
            name = "variable_cost",
            data = data,
            resolution = Dates.Hour(1))

set_variable_cost!(sys_DA, generator, time_series_data)
```
The last line Gives the error:
```
ERROR: InfrastructureSystems.ConflictingInputsError("forecast count 1 does not match system count 366")
Stacktrace:
 [1] _check_forecast_params(::InfrastructureSystems.TimeSeriesParameters, ::InfrastructureSystems.TimeSeriesParameters) at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/time_series_parameters.jl:129
 [2] _check_time_series(::InfrastructureSystems.TimeSeriesParameters, ::InfrastructureSystems.TimeSeriesParameters) at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/time_series_parameters.jl:115
 [3] check_add_time_series! at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/time_series_parameters.jl:165 [inlined]
 [4] check_add_time_series!(::InfrastructureSystems.TimeSeriesParameters, ::Deterministic) at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/time_series_parameters.jl:148
 [5] _attach_time_series_and_serialize!(::InfrastructureSystems.SystemData, ::ThermalStandard, ::InfrastructureSystems.DeterministicMetadata, ::Deterministic; skip_if_present::Bool) at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/system_data.jl:178
 [6] add_time_series!(::InfrastructureSystems.SystemData, ::ThermalStandard, ::Deterministic; skip_if_present::Bool) at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/system_data.jl:139
 [7] add_time_series! at /Users/andrewrosemberg/.julia/packages/InfrastructureSystems/6GZHV/src/system_data.jl:137 [inlined]
 [8] add_time_series! at /Users/andrewrosemberg/.julia/packages/PowerSystems/PnjZj/src/base.jl:873 [inlined]
 [9] set_variable_cost!(::System, ::ThermalStandard, ::Deterministic) at /Users/andrewrosemberg/.julia/packages/PowerSystems/PnjZj/src/models/cost_function_timeseries.jl:125
 [10] top-level scope at REPL[174]:1
```

Adding as `SingleTimeSeries` before the `transform_single_time_series!` gives:
```
ERROR: InfrastructureSystems.ConflictingInputsError("forecast parameter mismatch")
```

**Comment by daniel-thom** [comment]
This is working as designed. @jd-lara made it a requirement that all forecasts have to have identical parameters. We could add code to truncate the existing forecasts. @jd-lara?

**Comment by andrewrosemberg** [comment]
So for the `SingleTimeSeries `, I get the requirement. However, for forecasts, I would say that the check for a similar count is not great. I would much prefer to have a count check when I run a `Simulation` where it only checks for the period I will run the simulation for.

Nevertheless, extending on @daniel-thom comment about being able to truncate forecasts (similar to `transform_single_time_series! ` but for forecasts) but to also combine them (more or less the inverse of `transform_single_time_series!`) would be great!

**Comment by andrewrosemberg** [comment]
@jd-lara and @daniel-thom, let me know if the short term suggestion pleases you, and if it's easy to implement. I can create the PR given my pressing need.

**Comment by daniel-thom** [comment]
@andrewrosemberg Changing the errors (exceptions) to warning log messages would be trivial. Search for `throw` in this file: https://github.com/NREL-SIIP/InfrastructureSystems.jl/blob/master/src/time_series_parameters.jl. The system functions like `get_forecast_initial_times` will return information for the first forecast you stored. Otherwise, the system should work fine.

I'll defer to @jd-lara on the short term fix.
- You could make this change locally only.
- You could make the behavior customizable with an environment variable (keeping the current default). I would have no problem merging that. Jose may or may not agree.
- You could add a System kwarg parameter called something like `require_forecast_consistency` and pipe it through the stack. I think you would find this painful and don't recommend it. I could do it next week. But I'm not sure that I would want to if we have something more elegant planned for a long-term solution.

**Comment by jd-lara** [comment]
The choice here was to guarantee that the data in a system is always complete and consistent. If the data isn't consistent then we could run into reproducibility problems. For instance, if the data only has time series values for a date range and other for other date ranges, it could lead to inconsistencies. 

@andrewrosemberg the options you propose are useful for a specific setting but can create multiple problems. In general, we are conservative when enabling these features since very easily can become a problem. 

The option you propose would imply that we would have to decide what to do if the additional generator has a time series start_stop time outside of the system's and how do we address these cases. For instance, if the system has a time series for `2020-01-01` to `2020-03-31` but the user adds forecasts with the initial time `2020-03-01` to `2020-04-30`. It isn't clear if now we have to extend the system count or throw an error, etc. 

@daniel-thom we discussed at length many scenarios of users adding data in ways that would be unsustainable for us to guarantee consistency and would have to relax the guarantees we can provide for a system. 

The most viable solution is to provide the option to truncate the data in the system if the user only wants to use a subset such that the serialized system is consistent with the addition of partial data.

**Comment by jd-lara** [comment]
The documentation of time series has been significantly expanded to address the confusions https://nrel-siip.github.io/PowerSystems.jl/stable/modeler_guide/time_series/
