### ISSUE TITLE
Allow AREA type in BUS section to be Decimal, not just Integer

### ISSUE THREAD

**Issue by egbutter** [NREL-SIIP/PowerSystems.jl#688]
Attempted to parse a PSSE raw file, and the parser raised an error that value `0.000` for AREA in section BUS is not of type `Int64`. PSSE allows the AREA section to be Decimal type too. 

```
sys =  System(PowerModelsData(joinpath(home_dir, "XXX.raw")));

Parsing failed at line 4: value '0.000' for AREA in section BUS is not of type Int64
```

**Comment by claytonpbarrows** [comment]
So, what happens if you give PSSE an area value of 1.5? Does it round it, or does it just work?

The reason I ask is because we need the area to be an Int, and it's not exactly clear what to do if the value has a nonzero decimal. I can add code to handle the `x.000` cases, but it will still fail if the decimal is nonzero, so I'm somewhat reluctant to do so. 

Also, this is using code borrowed from PowerModels.jl and any solution would likely result in a PR there, so input from @ccoffrin would be helpful.

**Comment by ccoffrin** [comment]
According to the documentation of the RAW v33, in the bus table `AREA` must be an integer from 1 to 9999, and has a default of 1.  I presume that PSSE is interpreting `0.0` as `1` in this case.

My inclination is that the PSSE data file is incorrect. We could consider updating the parser to be robust to this situation by replace any invalid values with the default of `1`.

**Comment by claytonpbarrows** [comment]
Irrespective of RAW v33 behavior, I'd be annoyed if I had a case with areas of `1.0, 1.0, 1.0` and I changed them to `1.0, 2.0, 3.0` but they all defaulted back to `1` (even with a warning). I'd prefer the parser to behave as the PowerModels.jl parser does now and just give me an error for an invalid value.

@egbutter and @ccoffrin what do you think?

**Comment by ccoffrin** [comment]
I prefer to enforce these are integer values from 1 to 9999.  This follows from the PSSE docs.

**Comment by claytonpbarrows** [comment]
@egbutter I'm going to close this in favor of sticking with the current behavior that appears to be consistent with the RAW v33 documentation.

**Comment by egbutter** [comment]
Ok, thank you guys!

**Comment by ccoffrin** [comment]
You might also check the RAW file version. Columns and tables have been added over time, some older RAW files might have this issue.
