### ISSUE TITLE
Branch rating validation always assumes that rate is per-unit

### ISSUE THREAD

**Issue by danielolsen** [NREL-SIIP/PowerSystems.jl#721]
Warning appear when instantiating a `System`, ultimately coming from https://github.com/NREL-SIIP/PowerSystems.jl/blob/master/src/utils/IO/branchdata_checks.jl#L136

It seems that we are allowed to specify branches in natural units, based on the example at https://github.com/NREL-SIIP/SIIPExamples.jl/blob/master/script/2_PowerSystems_examples/US_config/us_descriptors.yaml#L8

**Comment by claytonpbarrows** [comment]
Hi @danielolsen,
The branchdata_checks.jl checks are in P.U. because all of the data is stored in P.U. The example you cite is the configuration file for the tabular data parser. The `natural_units` entry indicates that the source data is in natural units and will get converted to P.U. if it needs to (which it does in this case). The data get's stored in P.U., but the interfaces like `get_rate(b)` will return values in the units system that the `System` is set to (e.g. `set_units_base_system!(sys, "NATURAL_UNITS")`). So, the SIL check should handle things appropriately.
If you want to share an example, I can help diagnose.

**Comment by danielolsen** [comment]
I see what's happening now, it's a problem with our input data, not the code. Thanks!

I was using the 08_US_System example in SIIPExamples.jl, with a few small changes to the notebook where the example seems to have drifted from the dependent packages:
- `int2bustype(b) = replace(split(string(PowerSystems.BusTypes.BusType(b)), ".")[end], "]" => "")` is replaced by `int2bustype(b) = replace(split(string(PowerSystems.BusTypes(b + 1)), ".")[end], "]" => "")` when parsing bus data.
- `branch = join(..., kind = :left)` is replaced by `branch = leftjoin(...)` when parsing branch data.

**Comment by claytonpbarrows** [comment]
I also found some of those issues. I've pushed my fixes to master.

**Comment by claytonpbarrows** [comment]
@danielolsen based on your comment above, I'll close this issue.
