### ISSUE TITLE
Error when parsing a RAW (PSSE) file 

### ISSUE THREAD

**Issue by tavovalmo1983** [NREL-SIIP/PowerSystems.jl#852]
Hi, I am trying to build my own 11-bus (two areas) test system presented in Kundur's book. 

I used the following lines:
data_dir = ".../.../PSSE_11_bus_Kundur"
RAW_dir = joinpath(data_dir, "11BUS_KUNDUR.raw")
sys = System(RAW_dir)

Even when my .raw file has the same format as in your examples, I get the following KeyError:
![Captura](https://user-images.githubusercontent.com/16103951/151866827-448628f9-efdf-4816-b2d0-4472ba655dda.JPG)

**Comment by jd-lara** [comment]
Can you provide the raw file also to reproduce?

**Comment by tavovalmo1983** [comment]
Sure, here is as a csv file

[11BUS_KUNDUR.csv](https://github.com/NREL-SIIP/PowerSystems.jl/files/7974051/11BUS_KUNDUR.csv)

**Comment by jd-lara** [comment]
@tavovalmo1983 the issue is that the file doesn't conform to PTI v32 standard that requires two new lines after the header. As a result, the parser is ignoring bus 1 so when it tries to find the bus for the generator that line was ignored. 

current format: 

![image](https://user-images.githubusercontent.com/16385323/151872333-8cb16885-4b52-415a-9e99-91e3cd8326d0.png)

required format 

![image](https://user-images.githubusercontent.com/16385323/151872389-2b0d59bd-7ef0-4061-a981-f8f0e919ecb8.png)

This is required because PTI's original format doesn't have a line-break syntax. Adding the extra line break allows us to parse the data 

![image](https://user-images.githubusercontent.com/16385323/151872596-165328d3-34e8-45d1-a0d4-1a9dbaeb954b.png)

@ccoffrin and @claytonpbarrows maybe adding detection for the 2 line breaks would be useful to catch these cases.

**Comment by tavovalmo1983** [comment]
Thanks!
