### ISSUE TITLE
Error in Ymatrix when building model from RAW file

### ISSUE THREAD

**Issue by tavovalmo1983** [NREL-SIIP/PowerSystems.jl#853]
Hi, I have a 4-bus test system with an off-nominal tap position transformer. The resulting Ymatrix is wrong. This occurs when I use a raw (PSSE) file. However, when I build the same system with Matpower, I have no problems. Please see attached.  
![Ybus_wrong](https://user-images.githubusercontent.com/16103951/152071334-00d99a38-114a-426f-813c-e4807bfb7728.JPG)
[TVC_SystemMATPOWER.csv](https://github.com/NREL-SIIP/PowerSystems.jl/files/7982672/TVC_SystemMATPOWER.csv)
[TVC_SystemRAWPSSE.csv](https://github.com/NREL-SIIP/PowerSystems.jl/files/7982673/TVC_SystemRAWPSSE.csv)

**Comment by jd-lara** [comment]
It looks like the data has a problem, the `r` and `x` values for the tap transformer `"BUS4-BUS3-i_4"` are 0.0. I am not sure how PSS/e or Matpower handles these cases internally but we don't support it. 

![image](https://user-images.githubusercontent.com/16385323/152084024-a03b13e0-f1a9-4865-849d-d196d01408d8.png)

I added some protection to detect these cases just in case in PR #854

**Comment by tavovalmo1983** [comment]
This transformer has a reactance value different from zero in the sav file. Something is wrong when PSSE converts from sav to raw file.

**Comment by jd-lara** [comment]
@tavovalmo1983 The issue is that in the data set the base voltage of the transformer is set to 0.0 and the parser does a per-unit transform of the transformer from its base to the system base. Since the base voltage is set at 0.0, the transformation results in a base impedance of 0.0. I opened another PR to catch this issue. 

<img width="949" alt="image" src="https://user-images.githubusercontent.com/16385323/152187898-67bc4142-83db-48b2-96b9-5225fb7aae59.png">
